// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Counter: typeof import('./components/Counter.vue')['default']
    CurrencyMenuItem: typeof import('./components/CurrencyMenuItem.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    GuestMenu: typeof import('./components/GuestMenu.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    Link: typeof import('./components/Link.vue')['default']
    LocaleMenuItem: typeof import('./components/LocaleMenuItem.vue')['default']
    LocationAutoComplete: typeof import('./components/LocationAutoComplete.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SpinButton: typeof import('./components/SpinButton.vue')['default']
    UserMenu: typeof import('./components/UserMenu.vue')['default']
  }
}

export {}
