// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CarbonCampsite: typeof import('~icons/carbon/campsite')['default']
    CarbonPedestrian: typeof import('~icons/carbon/pedestrian')['default']
    Counter: typeof import('./components/Counter.vue')['default']
    CurrencyMenuItem: typeof import('./components/CurrencyMenuItem.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    GuestMenu: typeof import('./components/GuestMenu.vue')['default']
    Header: typeof import('./components/Header.vue')['default']
    LocaleMenuItem: typeof import('./components/LocaleMenuItem.vue')['default']
    LocationAutoComplete: typeof import('./components/LocationAutoComplete.vue')['default']
    MdiAccount: typeof import('~icons/mdi/account')['default']
    MdiAccountPlus: typeof import('~icons/mdi/account-plus')['default']
    MdiBullhorn: typeof import('~icons/mdi/bullhorn')['default']
    MdiSearch: typeof import('~icons/mdi/search')['default']
    MdiTranslate: typeof import('~icons/mdi/translate')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SpinButton: typeof import('./components/SpinButton.vue')['default']
    UserMenu: typeof import('./components/UserMenu.vue')['default']
  }
}

export {}
